name: 'assume-aws-role-from-gcp-action'
description: 'Assume AWS Role with GCP Service Account OIDC Token'
branding:
  icon: 'cloud'
  color: 'orange'
inputs:
  aws_region:
    description: 'AWS Region (default: us-east-1)'
    default: 'us-east-1'
  role_to_assume:
    description: 'ARN of the role to assume (e.g. arn:aws:iam::123456789012:role/role-name)'
    required: true
  role_session_name:
    description: 'Role session name (default: GitHubActions)'
    default: 'GitHubActions'
  role_duration_seconds:
    description: 'Role duration in seconds (default: 6 hours, 1 hour for OIDC/specified aws-session-token)'
    default: '21600'
outputs:
  aws_account_id:
    description: 'The AWS account ID for the provided credentials'
runs:
  using: 'node16'
  main: 'dist/index.js'
