name: "assume-aws-role-from-gcp-action"
description: "Assume AWS Role with GCP Service Account OIDC Token"
branding:
  icon: "cloud"
  color: "orange"
inputs:
  role-to-assume:
    description: >-
      Use the provided credentials to assume an IAM role and configure the Actions
      environment with the assumed role credentials rather than with the provided
      credentials
    required: false
  role-session-name:
    description: "Role session name (default: GitHubActions)"
    default: "GitHubActions"
  role-duration-seconds:
    description: "Role duration in seconds (default: 6 hours, 1 hour for OIDC/specified aws-session-token)"
    default: "21600"
outputs:
  aws-account-id:
    description: "The AWS account ID for the provided credentials"
runs:
  using: "docker"
  image: "ghcr.io/omercnet/assume-aws-role-from-gcp-action"
  args:
    - ${{ inputs.role-to-assume }}
    - ${{ inputs.role-session-name }}
    - ${{ inputs.role-duration-seconds }}
